# Generated by Django 4.0.4 on 2022-05-29 20:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('smile', '0002_customuser_dd_alter_customuser_prpricingrulename'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='category',
            name='cImage',
        ),
    ]
