# Generated by Django 4.0.4 on 2022-05-29 21:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('smile', '0003_remove_category_cimage'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProductPricingList',
            fields=[
                ('pplID', models.AutoField(primary_key=True, serialize=False)),
                ('userId', models.IntegerField()),
                ('productID', models.IntegerField()),
                ('productPrice', models.IntegerField()),
            ],
        ),
    ]
