# Generated by Django 4.0.4 on 2022-05-29 21:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('smile', '0004_productpricinglist'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productpricinglist',
            name='productID',
            field=models.CharField(default='', max_length=300),
        ),
        migrations.AlterField(
            model_name='productpricinglist',
            name='userId',
            field=models.CharField(default='', max_length=300),
        ),
    ]
