# Generated by Django 4.0.4 on 2022-05-29 22:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('smile', '0005_alter_productpricinglist_productid_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='productpricinglist',
            old_name='productID',
            new_name='productname',
        ),
        migrations.RenameField(
            model_name='productpricinglist',
            old_name='userId',
            new_name='username',
        ),
    ]
