# Generated by Django 4.0.4 on 2022-05-29 23:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('smile', '0006_rename_productid_productpricinglist_productname_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='productpricinglist',
            name='categoryname',
            field=models.CharField(default='', max_length=300),
        ),
    ]
