# Generated by Django 4.0.4 on 2022-05-31 18:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('smile', '0011_remove_product_pimage_remove_product_psaleprice_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='pSalePrice',
            field=models.CharField(default='', max_length=250),
        ),
    ]
