# Generated by Django 4.0.4 on 2022-05-31 18:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('smile', '0013_product_locationmarkup_product_pimage_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='locationMarkUp',
            new_name='pLoc',
        ),
        migrations.RemoveField(
            model_name='product',
            name='usernameID',
        ),
    ]
