# Generated by Django 4.0.4 on 2022-05-31 19:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('smile', '0016_remove_product_pimage'),
    ]

    operations = [
        migrations.RenameField(
            model_name='productpricinglist',
            old_name='categoryMarkUp',
            new_name='cID',
        ),
        migrations.RenameField(
            model_name='productpricinglist',
            old_name='locationMarkUp',
            new_name='lID',
        ),
        migrations.RenameField(
            model_name='productpricinglist',
            old_name='priceMarkup',
            new_name='pID',
        ),
        migrations.RenameField(
            model_name='productpricinglist',
            old_name='usernameID',
            new_name='uID',
        ),
        migrations.RemoveField(
            model_name='productpricinglist',
            name='categoryname',
        ),
        migrations.RemoveField(
            model_name='productpricinglist',
            name='productname',
        ),
        migrations.RemoveField(
            model_name='productpricinglist',
            name='username',
        ),
        migrations.AddField(
            model_name='productpricinglist',
            name='cMarkup',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='productpricinglist',
            name='lMarkup',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='productpricinglist',
            name='pMarkup',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
    ]
