# Generated by Django 4.0.4 on 2022-05-31 19:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('smile', '0017_rename_categorymarkup_productpricinglist_cid_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='productpricinglist',
            name='pName',
            field=models.CharField(default=0, max_length=220),
        ),
        migrations.AlterField(
            model_name='productpricinglist',
            name='cMarkup',
            field=models.IntegerField(default=1),
        ),
        migrations.AlterField(
            model_name='productpricinglist',
            name='lMarkup',
            field=models.IntegerField(default=1),
        ),
        migrations.AlterField(
            model_name='productpricinglist',
            name='pMarkup',
            field=models.IntegerField(default=1),
        ),
    ]
