# Generated by Django 4.0.4 on 2022-05-31 22:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('smile', '0019_remove_product_ploc_customuser_ploc'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customuser',
            name='pLoc',
        ),
    ]
