# Generated by Django 4.0.4 on 2022-05-31 22:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('smile', '0021_customuser_ploc'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='pLoc',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='smile.location'),
        ),
    ]
