# Generated by Django 4.0.4 on 2022-06-02 06:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('smile', '0026_alter_customuser_ploc'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productpricinglist',
            name='pName',
            field=models.CharField(default='', max_length=220),
        ),
    ]
